/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Mate */

#ifndef _Included_Mate
#define _Included_Mate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Mate
 * Method:    suma
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_Mate_suma
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     Mate
 * Method:    resta
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_Mate_resta
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     Mate
 * Method:    multip
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_Mate_multip
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     Mate
 * Method:    divs
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_Mate_divs
  (JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
